import type {CreatureSpecies, NeedKey, WildSpecies} from '../types';

export type CareAction='feed'|'groom'|'play'|'read';
export type FieldRole='Pathfinder'|'Restorer'|'Guardian'|'Forager'|'Sky Scout'|'Trailbreaker'|'Ridge Runner'|'Mist Reader'|'Ancient Guide'|'Lightfinder'|'Rain Listener'|'Pool Delver'|'Squall Walker'|'Basin Keeper';

export interface CreatureProfile {
  role:FieldRole;
  active:{name:string;description:string;kind:'material'|'energy'|'marks'|'trail-kit';amount:number;material?:string};
  passive:string;
  region:string;
  encounterSpecies:WildSpecies[];
  encounterBonus:number;
  gathering:{description:string;material?:string;quantity?:number;marksPercent?:number};
  preferredCare:CareAction;
  favoriteFood:string;
  favoriteActivity:string;
  quest:{title:string;description:string;bondGoal:number;reward:string};
  lore:[string,string,string,string];
  energyRegenMultiplier:number;
}

export const creatureProfiles:Record<CreatureSpecies,CreatureProfile>={
  spriggle:{role:'Pathfinder',active:{name:'Keen Nose',description:'Gather 2 Mossfiber for the next trail.',kind:'material',amount:2,material:'mossfiber'},passive:'Reads observation clues with unusual precision.',region:'Mossmere',encounterSpecies:['mosskit','veilfin'],encounterBonus:10,gathering:{description:'+1 Mossfiber on each forage contract.',material:'mossfiber',quantity:1},preferredCare:'read',favoriteFood:'Mossberry Tart',favoriteActivity:'Mapping hidden paths',quest:{title:'Every Turning Leaf',description:'Reach Kindred bond by recording trails together.',bondGoal:75,reward:'Leafscript Mantle'},lore:['Spriggles remember paths by scent.','A trusted Spriggle marks safe water with curled leaves.','Old journals call them the first mapmakers.','Pip can now recognize your footsteps before you arrive.'],energyRegenMultiplier:1},
  mallowisp:{role:'Restorer',active:{name:'Soothing Glow',description:'Restore 24 Energy to your active companion.',kind:'energy',amount:24},passive:'Recovers Energy 25% faster between expeditions.',region:'Cloudfen',encounterSpecies:['galecrest','veilfin'],encounterBonus:8,gathering:{description:'+1 Soft Moss after the first daily contract.',material:'softmoss',quantity:1},preferredCare:'groom',favoriteFood:'Sunpetal Tea',favoriteActivity:'Listening to rainfall',quest:{title:'Light Between Reeds',description:'Reach Kindred bond through quiet care.',bondGoal:75,reward:'Reedlight Ribbon'},lore:['Mallowisps dim their glow when listening.','Their light follows the rhythm of nearby rain.','Cloudfen guides once navigated by Mallowisp choirs.','A lifelong companion keeps one warm spark only for you.'],energyRegenMultiplier:1.25},
  bramblet:{role:'Guardian',active:{name:'Briar Cache',description:'Prepare 1 Trail Kit without spending materials.',kind:'trail-kit',amount:1},passive:'Holds steady during route and Resolve challenges.',region:'Amber Reach',encounterSpecies:['cragback','old-warden'],encounterBonus:10,gathering:{description:'+10% Marks on forage contracts.',marksPercent:10},preferredCare:'play',favoriteFood:'Brightroot slices',favoriteActivity:'Pushing fallen branches',quest:{title:'The Steady Way',description:'Reach Kindred bond by facing the trail together.',bondGoal:75,reward:'Briar Guard Badge'},lore:['Bramblets test every bridge before crossing.','A happy Bramblet collects smooth amber stones.','Reach wardens once trusted them to warn whole camps.','Its deepest rumble means: the path is safe.'],energyRegenMultiplier:.9},
  mosskit:{role:'Forager',active:{name:'Moss Cache',description:'Gather 2 Soft Moss from a hidden cache.',kind:'material',amount:2,material:'softmoss'},passive:'Finds more woodland materials while foraging.',region:'Mossmere',encounterSpecies:['mosskit','galecrest'],encounterBonus:8,gathering:{description:'+1 Mossfiber and +1 Soft Moss per contract.',material:'mossfiber',quantity:1},preferredCare:'feed',favoriteFood:'Mossberry Offering',favoriteActivity:'Searching root hollows',quest:{title:'A Cache Shared',description:'Reach Trusted bond and earn a Mosswoven Scarf.',bondGoal:50,reward:'Mosswoven Scarf'},lore:['Mosskits hide supplies in three separate caches.','They share the safest cache only with companions.','Their whiskers sense hollow roots beneath deep moss.','This Mosskit has begun leaving treasures beside your bedroll.'],energyRegenMultiplier:1},
  galecrest:{role:'Sky Scout',active:{name:'Windfall',description:'Gather 2 Cloudglass carried by an upper current.',kind:'material',amount:2,material:'cloudglass'},passive:'Excels at timing challenges and Cloudfen routes.',region:'Cloudfen',encounterSpecies:['galecrest','emberstride'],encounterBonus:11,gathering:{description:'+1 Cloudglass after a high-scoring forage run.',material:'cloudglass',quantity:1},preferredCare:'play',favoriteFood:'Sunpetal Tea',favoriteActivity:'Racing crosswinds',quest:{title:'Where Currents Meet',description:'Reach Trusted bond while learning the upper winds.',bondGoal:50,reward:'Galecrest Pennant'},lore:['Galecrests see wind as shifting bands of color.','Their longest feathers hum before a storm.','Young scouts follow them to find clear air.','It circles once overhead whenever you leave camp.'],energyRegenMultiplier:1.1},
  cragback:{role:'Trailbreaker',active:{name:'Stone Reserve',description:'Recover 16 Energy through a sheltered rest.',kind:'energy',amount:16},passive:'Shrugs off difficult route and guardian approaches.',region:'Amber Reach',encounterSpecies:['cragback','old-warden'],encounterBonus:13,gathering:{description:'+1 Sunscale on the final daily contract.',material:'sunscale',quantity:1},preferredCare:'groom',favoriteFood:'Mineral-rich Brightroot',favoriteActivity:'Building stone circles',quest:{title:'Weight of Trust',description:'Reach Trusted bond without rushing the journey.',bondGoal:50,reward:'Stonepath Tack'},lore:['Cragbacks grow a new ridge for every migration.','They sleep facing the oldest mountain they know.','Their herds remember safe trails for generations.','This one lowers its armored brow so you can rest beside it.'],energyRegenMultiplier:.8},
  emberstride:{role:'Ridge Runner',active:{name:'Ridge Sprint',description:'Earn 45 Marks by carrying a dispatch.',kind:'marks',amount:45},passive:'Dominates timing trials, but offers little tracking help.',region:'Amber Reach',encounterSpecies:['emberstride','galecrest'],encounterBonus:14,gathering:{description:'+12% Marks, with no extra materials.',marksPercent:12},preferredCare:'play',favoriteFood:'Peppered Sunpetals',favoriteActivity:'Dawn ridge sprints',quest:{title:'Outrun the Sunrise',description:'Reach Trusted bond through bold expeditions.',bondGoal:50,reward:'Emberwake Streamers'},lore:['Emberstrides leave warm prints in cold stone.','They race storms to sharpen their senses.','One ancient runner carried messages across the Reach in a night.','It now matches its pace to yours on narrow ledges.'],energyRegenMultiplier:1},
  veilfin:{role:'Mist Reader',active:{name:'Mist Pearl',description:'Gather 2 Moondrop from a silent current.',kind:'material',amount:2,material:'moondrop'},passive:'Uncovers extra guidance in observation challenges.',region:'Cloudfen',encounterSpecies:['veilfin','mosskit'],encounterBonus:14,gathering:{description:'+1 Moondrop after the second daily contract.',material:'moondrop',quantity:1},preferredCare:'read',favoriteFood:'Cool Sunpetal Tea',favoriteActivity:'Watching constellations',quest:{title:'The Unwritten Current',description:'Reach Trusted bond and chart its silent route.',bondGoal:50,reward:'Veilfin Constellation'},lore:['Veilfins swim through mist as though it were water.','Their fins mirror stars hidden above the clouds.','They vanish when voices become too loud.','A faint constellation appears whenever it waits for you.'],energyRegenMultiplier:1.05},
  'old-warden':{role:'Ancient Guide',active:{name:'Warden’s Compass',description:'Gather 1 Relic Shard from an awakened marker.',kind:'material',amount:1,material:'relic-shard'},passive:'Exceptional in ruin routes, but slow to recover Energy.',region:'The Ruins',encounterSpecies:['old-warden'],encounterBonus:18,gathering:{description:'+1 Lumenstone on the final contract.',material:'lumenstone',quantity:1},preferredCare:'read',favoriteFood:'No known favorite',favoriteActivity:'Restoring trail markers',quest:{title:'Names in the Stone',description:'Reach Trusted bond and restore a forgotten marker.',bondGoal:50,reward:'Warden Sigil'},lore:['The Warden carries fragments of many vanished roads.','Its silence is a language of posture and light.','No journal agrees on how long it guarded the ruins.','It has added your name to the paths it remembers.'],energyRegenMultiplier:.7},
  glintmoth:{role:'Lightfinder',active:{name:'Earshine',description:'Gather 2 Glassreed from a hidden pool.',kind:'material',amount:2,material:'glassreed'},passive:'Finds bright trails beneath Glassroot bridges.',region:'Glassroot Basin',encounterSpecies:['glintmoth','prismhart'],encounterBonus:10,gathering:{description:'+1 Glassreed while foraging.',material:'glassreed',quantity:1},preferredCare:'play',favoriteFood:'Saltbloom petals',favoriteActivity:'Chasing reflected lanterns',quest:{title:'Lights Under Roots',description:'Reach Trusted bond while mapping hidden pools.',bondGoal:50,reward:'Glint-Ear Ribbon'},lore:['Glintmoths hear light striking crystal.','They sleep beneath warm root arches.','Their scales point toward clean water.','It leaves a shining scale on your journal clasp.'],energyRegenMultiplier:1.15},
  reedstalker:{role:'Rain Listener',active:{name:'Rain Reading',description:'Gather 1 Root Pearl from a rain-current sign.',kind:'material',amount:1,material:'rootpearl'},passive:'Excels at observation when basin weather shifts.',region:'Glassroot Basin',encounterSpecies:['reedstalker','prismhart'],encounterBonus:12,gathering:{description:'+1 Glassreed after careful searching.',material:'glassreed',quantity:1},preferredCare:'read',favoriteFood:'Mineral minnows',favoriteActivity:'Listening to distant rain',quest:{title:'A Language of Posture',description:'Reach Trusted bond and record its rain signs.',bondGoal:50,reward:'Reedscript Charm'},lore:['Each leg answers a different current.','Its whiskers taste minerals in rain.','Stillness is its most welcoming gesture.','It now bows one reed-leg when you approach.'],energyRegenMultiplier:1},
  flintcap:{role:'Pool Delver',active:{name:'Silt Vault',description:'Gather 2 Saltbloom from a buried hollow.',kind:'material',amount:2,material:'saltbloom'},passive:'Brings unmatched Resolve to flooded routes.',region:'Glassroot Basin',encounterSpecies:['flintcap','hollowhorn'],encounterBonus:13,gathering:{description:'+1 Saltbloom on later contracts.',material:'saltbloom',quantity:1},preferredCare:'groom',favoriteFood:'Brined brightroot',favoriteActivity:'Clearing silt channels',quest:{title:'The Buried Channel',description:'Reach Trusted bond and reopen an old pool.',bondGoal:50,reward:'Flintcap Buckle'},lore:['Flintcaps sharpen claws on glass roots.','Their throat marks brighten near springs.','They build dry chambers below flooded ground.','It trusts you to brush mud from its oldest plate.'],energyRegenMultiplier:.85},
  prismhart:{role:'Squall Walker',active:{name:'Refracted Step',description:'Earn 55 Marks guiding travelers through rain.',kind:'marks',amount:55},passive:'Swift and precise during timing challenges.',region:'Glassroot Basin',encounterSpecies:['prismhart','galecrest'],encounterBonus:15,gathering:{description:'+12% Marks during field contracts.',marksPercent:12},preferredCare:'read',favoriteFood:'Fresh Saltbloom',favoriteActivity:'Walking beneath prism rain',quest:{title:'Four Colors Returning',description:'Reach Trusted bond and chart a vanishing trail.',bondGoal:50,reward:'Prismhart Veil'},lore:['Prismharts appear only when rain divides light.','Their antlers never cast the same color twice.','Old basin maps use their paths as seasonal roads.','It waits at the edge of squalls for you.'],energyRegenMultiplier:1.05},
  hollowhorn:{role:'Basin Keeper',active:{name:'Rootsong',description:'Restore 20 Energy through a guardian call.',kind:'energy',amount:20},passive:'The strongest guardian match, balanced by slow recovery.',region:'Glassroot Basin',encounterSpecies:['hollowhorn'],encounterBonus:20,gathering:{description:'+1 Root Pearl on final contracts.',material:'rootpearl',quantity:1},preferredCare:'groom',favoriteFood:'Ancient salt lichen',favoriteActivity:'Restoring root markers',quest:{title:'The Basin Remembers',description:'Reach Trusted bond after restoring every marker.',bondGoal:50,reward:'Hollowhorn Crown'},lore:['Its horn carries the voices of hollow roots.','Prism scars record storms survived.','The guardian wakes only for paths worth preserving.','Its rootsong now includes your footsteps.'],energyRegenMultiplier:.65},
};

export const bondLevels=[{min:0,name:'New Companion'},{min:25,name:'Familiar'},{min:50,name:'Trusted'},{min:75,name:'Kindred'},{min:90,name:'Lifelong'}] as const;
export const bondMilestones=[25,50,75,90] as const;
export function bondLevel(bond:number){return [...bondLevels].reverse().find(level=>bond>=level.min)??bondLevels[0]}
export function milestoneIds(bond:number){return bondMilestones.filter(value=>bond>=value).map(value=>`bond-${value}`)}
export function preferredNeed(action:CareAction):NeedKey{return action==='feed'?'hunger':action==='groom'?'health':action==='play'?'mood':'bond'}
