import {describe,expect,it} from 'vitest';
import {initialState,awardForage,care,encounterTuning,recoverCreature,selectCreature,starterCreature} from '../game';
import {migrateGameState,CURRENT_SCHEMA_VERSION} from '../firebase';
import {activateCreatureAbility,claimCreatureQuest,hydrateCreature} from './creatureEngine';
import {bondLevel,creatureProfiles} from './creatureData';

describe('creature identities and bond progression',()=>{
 it('defines a complete, distinct field identity for every species',()=>{expect(Object.keys(creatureProfiles)).toHaveLength(14);expect(new Set(Object.values(creatureProfiles).map(profile=>profile.role)).size).toBe(14);expect(new Set(Object.values(creatureProfiles).map(profile=>profile.active.name)).size).toBe(14)});
 it('assigns bond levels at stable milestone thresholds',()=>{expect(bondLevel(24).name).toBe('New Companion');expect(bondLevel(25).name).toBe('Familiar');expect(bondLevel(75).name).toBe('Kindred');expect(bondLevel(100).name).toBe('Lifelong')});
 it('adds preference bond without changing the base care action',()=>{const state=initialState('spriggle');expect(care(state,'read',1).needs.bond).toBe(89);expect(care(state,'groom',1).needs.bond).toBe(86)});
 it('gives specialized companions advantages only in their matching encounters',()=>{const state=initialState('spriggle');const matching=encounterTuning(state,'mosskit');const offRole=encounterTuning(state,'cragback');expect(matching.roleBonus).toBeGreaterThan(0);expect(offRole.roleBonus).toBe(0);expect(matching.score).toBe(matching.rawScore+matching.roleBonus)});
 it('applies gathering bonuses without bypassing the daily contract cap',()=>{const state=initialState('spriggle');const first=awardForage(state,50,1);expect(first.materials.mossfiber).toBe(2);const capped=awardForage({...first,foragePlays:3,forageDate:'1970-01-01'},100,1);expect(capped.dewdrops).toBe(first.dewdrops)});
 it('limits active abilities to once per UTC day',()=>{const state=initialState('spriggle');const first=activateCreatureAbility(state,'starter',1);const second=activateCreatureAbility(first,'starter',2);expect(first.materials.mossfiber).toBe(2);expect(second.materials.mossfiber).toBe(2);expect(second.lastAction).toContain('tomorrow')});
 it('requires the creature to be active before using its ability',()=>{const state=initialState();const other=hydrateCreature({...starterCreature('mallowisp','Luma'),id:'other'});const next=activateCreatureAbility({...state,creatures:[...state.creatures,other]},'other',1);expect(next.creatures.find(entry=>entry.id==='other')?.abilityUsedDate).toBe('')});
 it('switches the displayed bond with the active creature to prevent bond copying',()=>{const state=initialState();const other=hydrateCreature({...starterCreature('mallowisp','Luma',25),id:'other'});const selected=selectCreature({...state,creatures:[...state.creatures,other]},'other');expect(selected.needs.bond).toBe(25);expect(care(selected,'groom',1).creatures.find(entry=>entry.id==='other')?.bond).toBe(32)});
 it('claims each personal quest exactly once and persists the cosmetic',()=>{const state=initialState('spriggle');const ready={...state,creatures:state.creatures.map(creature=>({...creature,bond:75}))};const claimed=claimCreatureQuest(ready,'starter');const repeated=claimCreatureQuest(claimed,'starter');expect(claimed.starpetals).toBe(state.starpetals+2);expect(claimed.cosmetics[0]).toContain('Leafscript Mantle');expect(repeated.starpetals).toBe(claimed.starpetals)});
 it('uses species-specific energy recovery rates',()=>{const now=1_000_000;const spriggle={...starterCreature('spriggle','Pip'),energy:0,energyUpdatedAt:now-240_000};const mallowisp={...starterCreature('mallowisp','Luma'),energy:0,energyUpdatedAt:now-240_000};expect(recoverCreature(spriggle,now).energy).toBe(0);expect(recoverCreature(mallowisp,now).energy).toBe(1)});
});

describe('schema 14 migration',()=>{
 it('hydrates new progress fields without changing existing economy or bond',()=>{const old=initialState('bramblet','Bram');const raw={...old,creatures:old.creatures.map(({abilityUsedDate:_,personalQuestClaimed:__,unlockedMilestones:___,...creature})=>creature)};const migrated=migrateGameState(raw as typeof old);expect(CURRENT_SCHEMA_VERSION).toBe(14);expect(migrated.creatures[0].bond).toBe(old.creatures[0].bond);expect(migrated.dewdrops).toBe(old.dewdrops);expect(migrated.creatures[0].abilityUsedDate).toBe('');expect(migrated.creatures[0].unlockedMilestones).toContain('bond-75')});
});
