import {useEffect,useMemo,useState} from 'react';
import {Coins,Eye} from 'lucide-react';
import {encounterTuning} from '../game';
import type {WildSpecies} from '../types';
const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;

export function Skyhop({close,reward}:{close:()=>void;reward:(n:number)=>void}){const[lane,setLane]=useState(1);const[round,setRound]=useState(0);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const cloud=useMemo(()=>[0,2,1,0,2,2,1,0][round%8],[round]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setLane(x=>Math.max(0,x-1));if(e.key==='ArrowRight')setLane(x=>Math.min(2,x+1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);const hop=()=>{if(done)return;const hit=lane===cloud;const next=round+1;setScore(x=>x+(hit?2:1));if(next===8){setDone(true);reward(Math.min(150,(score+(hit?2:1))*10))}else setRound(next)};return <div className="modal-back"><div className="game-modal" role="dialog" aria-modal="true" aria-label="Skyhop minigame"><button className="close" onClick={close}>×</button><p>Cloudfen pastime</p><h2>Skyhop</h2><span>Choose a lane, then hop. Land on the bright cloud for a bonus.</span><div className="sky-game"><div className="cloud-row">{[0,1,2].map(x=><i className={x===cloud?'bright':''} key={x}>☁</i>)}</div><div className="hopper" style={{left:`${lane*33.33+16.66}%`}}>✦</div></div>{done?<><h3>Trail complete · {score} points</h3><button className="primary" onClick={close}>Collect reward</button></>:<><div className="lane-controls"><button onClick={()=>setLane(x=>Math.max(0,x-1))}>← Left</button><button onClick={hop}>Hop {round+1}/8</button><button onClick={()=>setLane(x=>Math.min(2,x+1))}>Right →</button></div><small>Keyboard: ← → to move</small></>}</div></div>}

export function AdaptiveSurvey({species,round,tuning,onResult,close}:{species:WildSpecies;round:number;tuning:ReturnType<typeof encounterTuning>;onResult:(success:boolean)=>void;close:()=>void}){const[cursor,setCursor]=useState(0);const[result,setResult]=useState<boolean|null>(null);const targetSets:Record<WildSpecies,number[]>={mosskit:[68,34,57],galecrest:[72,29,61,43],cragback:[63,38,76,27,54],emberstride:[24,71,39,82,55],veilfin:[66,31,77,43,21,58],'old-warden':[50,26,74,38,62,18,84]};const targets=targetSets[species];const target=targets[round%targets.length];const half=tuning.windowPct/2;useEffect(()=>{let direction=1;const timer=setInterval(()=>setCursor(value=>{if(value>=98)direction=-1;if(value<=2)direction=1;return value+direction*tuning.step}),26);return()=>clearInterval(timer)},[tuning.step]);const read=()=>{if(result!==null)return;const success=Math.abs(cursor-target)<=half;setResult(success);onResult(success)};const names:Record<WildSpecies,string>={mosskit:'Mosskit',galecrest:'Galecrest',cragback:'Cragback',emberstride:'Emberstride',veilfin:'Veilfin','old-warden':'Old Warden'};const name=names[species];const gale=species==='galecrest';const crag=species==='cragback';return <div className="modal-back"><div className="game-modal trail-game" role="dialog" aria-modal="true" aria-label={`${name} tracking challenge`}><button className="close" onClick={close}>×</button><p>{gale?'Cloudfen wind reading':crag?'Amber Reach Resolve check':'Mossmere trail reading'}</p><h2>{gale?'Read the crosswind':crag?'Hold the line':'Read the trail'}</h2><span>{tuning.attribute} {tuning.score} versus difficulty {tuning.requirement}. Stronger attributes slow the marker and widen the target.</span><div className="trail-scene"><img src={asset(`creature-${species}.png`)} alt={`${name} encounter challenge`}/><div className="trail-track"><i style={{left:`${target-half}%`,width:`${tuning.windowPct}%`}}/><em style={{left:`${cursor}%`}}/></div></div>{result===null?<button className="primary" onClick={read}><Eye/> {gale?'Mark the wind':crag?'Brace':'Mark the trail'}</button>:<div className={result?'trail-result success':'trail-result failure'}><h3>{result?'Reading confirmed':'Reading missed'}</h3><p>{result?'Progress increased.':'No progress gained; Energy was still consumed.'}</p><button onClick={close}>Return to encounter</button></div>}</div></div>}

export function ForageRunV2({close,reward}:{close:()=>void;reward:(marks:number)=>void}){const tiles=['trail','berry','stone','feather','shell','bark','seed','crystal','bark','trail','crystal','shell','feather','seed','stone','berry'] as const;const symbols={trail:'⌁',berry:'◆',stone:'⬢',feather:'≋',shell:'◒',bark:'▥',seed:'✦',crystal:'◇'};const[open,setOpen]=useState<number[]>([]);const[matched,setMatched]=useState<number[]>([]);const[attempts,setAttempts]=useState(0);const[earned,setEarned]=useState<number|null>(null);const flip=(index:number)=>{if(earned!==null||open.length===2||open.includes(index)||matched.includes(index))return;if(open.length===0){setOpen([index]);return}const first=open[0];const nextAttempts=attempts+1;setAttempts(nextAttempts);if(tiles[first]===tiles[index]){const nextMatched=[...matched,first,index];setMatched(nextMatched);setOpen([]);if(nextMatched.length===16)setEarned(96)}else{setOpen([first,index]);setTimeout(()=>setOpen([]),650);if(nextAttempts>=14)setTimeout(()=>setEarned(matched.length/2*10),660)}};const collect=()=>{reward(earned??0);close()};return <div className="modal-back"><div className="game-modal forage-game forage-game-large" role="dialog" aria-modal="true" aria-label="Mossmere Forage Run"><button className="close" onClick={close}>×</button><p>Mossmere work contract</p><h2>Forage Run</h2><span>Match eight pairs of field signs in fourteen attempts. Clear the entire 4×4 route for a 16-Mark completion bonus.</span><div className="forage-status"><b>Attempts {attempts}/14</b><span>{matched.length/2}/8 pairs</span></div><div className="forage-grid forage-grid-4">{tiles.map((tile,index)=>{const shown=open.includes(index)||matched.includes(index);return <button className={shown?'revealed':''} disabled={matched.includes(index)||earned!==null} onClick={()=>flip(index)} key={index} aria-label={shown?tile:`Hidden field sign ${index+1}`}>{shown?symbols[tile]:'?'}</button>})}</div>{earned!==null?<div className="forage-result"><h3>{matched.length===16?'Route cleared':'Contract ended'}</h3><p>You earned {earned} Marks.</p><button className="primary" onClick={collect}><Coins/> Collect Marks</button></div>:<small>Three contracts are available per account each day.</small>}</div></div>}

