import {useEffect,useMemo,useState} from 'react';
import {Coins,Eye} from 'lucide-react';
import {encounterTuning} from '../game';
import type {WildSpecies} from '../types';
import {assistanceLevel,encounterProfiles,encounterRound} from './encounterData';
const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;

export function Skyhop({close,reward}:{close:()=>void;reward:(n:number)=>void}){const[lane,setLane]=useState(1);const[round,setRound]=useState(0);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const cloud=useMemo(()=>[0,2,1,0,2,2,1,0][round%8],[round]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setLane(x=>Math.max(0,x-1));if(e.key==='ArrowRight')setLane(x=>Math.min(2,x+1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);const hop=()=>{if(done)return;const hit=lane===cloud;const next=round+1;setScore(x=>x+(hit?2:1));if(next===8){setDone(true);reward(Math.min(150,(score+(hit?2:1))*10))}else setRound(next)};return <div className="modal-back"><div className="game-modal" role="dialog" aria-modal="true" aria-label="Skyhop minigame"><button className="close" onClick={close}>×</button><p>Cloudfen pastime</p><h2>Skyhop</h2><span>Choose a lane, then hop. Land on the bright cloud for a bonus.</span><div className="sky-game"><div className="cloud-row">{[0,1,2].map(x=><i className={x===cloud?'bright':''} key={x}>☁</i>)}</div><div className="hopper" style={{left:`${lane*33.33+16.66}%`}}>✦</div></div>{done?<><h3>Trail complete · {score} points</h3><button className="primary" onClick={close}>Collect reward</button></>:<><div className="lane-controls"><button onClick={()=>setLane(x=>Math.max(0,x-1))}>← Left</button><button onClick={hop}>Hop {round+1}/8</button><button onClick={()=>setLane(x=>Math.min(2,x+1))}>Right →</button></div><small>Keyboard: ← → to move</small></>}</div></div>}

export function EncounterChallenge({species,round,tuning,onResult,close}:{species:WildSpecies;round:number;tuning:ReturnType<typeof encounterTuning>;onResult:(success:boolean)=>void;close:()=>void}){
 const[fixedRound]=useState(round);const profile=encounterProfiles[species],choiceRound=encounterRound(species,fixedRound),kits=tuning.kits;const[cursor,setCursor]=useState(0);const[result,setResult]=useState<boolean|null>(null);const[selected,setSelected]=useState<number|null>(null);const targets:Record<'galecrest'|'emberstride',number[]>={galecrest:[72,29,61,43],emberstride:[24,71,39,82,55]};const target=profile.template==='timing'?targets[species as 'galecrest'|'emberstride'][fixedRound%targets[species as 'galecrest'|'emberstride'].length]:50;const half=tuning.windowPct/2;const assistance=assistanceLevel(tuning.score,tuning.requirement);
 useEffect(()=>{if(profile.template!=='timing'||result!==null)return;let direction=1;const timer=setInterval(()=>setCursor(value=>{if(value>=98)direction=-1;if(value<=2)direction=1;return value+direction*tuning.step}),26);return()=>clearInterval(timer)},[profile.template,result,tuning.step]);
 const finish=(success:boolean)=>{if(result!==null)return;setResult(success);onResult(success)};const submitTiming=()=>finish(Math.abs(cursor-target)<=half);const submitChoice=(index:number)=>{setSelected(index);finish(index===choiceRound?.correct)};
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(result!==null)return;if(profile.template==='timing'&&(event.key===' '||event.key==='Enter')){event.preventDefault();submitTiming()}else if(choiceRound&&['1','2','3'].includes(event.key))submitChoice(Number(event.key)-1)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 const assistCopy=assistance==='strong'?`${profile.attribute} advantage: ${profile.template==='timing'?'the safe window is wider and the marker is slower.':'your companion highlights the most reliable field sign.'}`:assistance==='matched'?`${profile.attribute} is suited to this challenge; careful reading will decide it.`:`This is a difficult ${profile.attribute} matchup. Failure costs Energy, but never blocks future sightings.`;
 return <div className="modal-back"><div className={`game-modal encounter-template ${profile.template}-challenge`} role="dialog" aria-modal="true" aria-label={`${profile.name} ${profile.template} challenge`}><button className="close" onClick={close}>×</button><p>{profile.region} · {profile.template} encounter</p><h2>{profile.action}</h2><span>{profile.intro}</span><div className={`matchup-note ${assistance}`}><b>{profile.attribute} {tuning.score}</b><span>Difficulty {tuning.requirement}</span><small>{assistCopy}</small></div>{result===null&&kits>0?<div className="trail-kit-option"><b>Trail Kit ready</b><small>Failure automatically consumes 1 kit and reduces Energy loss from 12 to 4 · {kits} held</small></div>:null}
 {profile.template==='timing'?<div className="timing-field"><img src={asset(`creature-${species}.png`)} alt={`${profile.name} moving through ${profile.region}`}/><div className="trail-track"><i style={{left:`${target-half}%`,width:`${tuning.windowPct}%`}}/><em style={{left:`${cursor}%`}}/></div>{result===null?<button className="primary" onClick={submitTiming}><Eye/> {profile.action}<small>Space or Enter</small></button>:null}</div>:choiceRound?<div className="field-choice"><h3>{choiceRound.prompt}</h3>{choiceRound.choices.map((choice,index)=><button className={`${selected===index?'selected ':''}${assistance==='strong'&&index===choiceRound.correct?'companion-hint':''}`} disabled={result!==null} onClick={()=>submitChoice(index)} key={choice}><b>{index+1}</b>{choice}{assistance==='strong'&&index===choiceRound.correct?<small>Companion’s read</small>:null}</button>)}</div>:null}
 {result!==null?<div className={result?'trail-result success':'trail-result failure'} role="status"><h3>{result?'Approach confirmed':'Approach missed'}</h3><p>{result?'Trust progress and a regional material were recorded.':`${choiceRound?choiceRound.guidance:'The timing window passed.'} ${kits>0?'Trail Kit protection reduced the Energy loss.':'Energy -12; another safe approach may remain today.'}`}</p><button onClick={close}>Return to encounter</button></div>:null}</div></div>
}

export function ForageRunV2({close,reward}:{close:()=>void;reward:(marks:number)=>void}){const tiles=['trail','berry','stone','feather','shell','bark','seed','crystal','bark','trail','crystal','shell','feather','seed','stone','berry'] as const;const symbols={trail:'⌁',berry:'◆',stone:'⬢',feather:'≋',shell:'◒',bark:'▥',seed:'✦',crystal:'◇'};const[open,setOpen]=useState<number[]>([]);const[matched,setMatched]=useState<number[]>([]);const[attempts,setAttempts]=useState(0);const[earned,setEarned]=useState<number|null>(null);const flip=(index:number)=>{if(earned!==null||open.length===2||open.includes(index)||matched.includes(index))return;if(open.length===0){setOpen([index]);return}const first=open[0];const nextAttempts=attempts+1;setAttempts(nextAttempts);if(tiles[first]===tiles[index]){const nextMatched=[...matched,first,index];setMatched(nextMatched);setOpen([]);if(nextMatched.length===16)setEarned(96)}else{setOpen([first,index]);setTimeout(()=>setOpen([]),650);if(nextAttempts>=14)setTimeout(()=>setEarned(matched.length/2*10),660)}};const collect=()=>{reward(earned??0);close()};return <div className="modal-back"><div className="game-modal forage-game forage-game-large" role="dialog" aria-modal="true" aria-label="Mossmere Forage Run"><button className="close" onClick={close}>×</button><p>Mossmere work contract</p><h2>Forage Run</h2><span>Match eight pairs of field signs in fourteen attempts. Clear the entire 4×4 route for a 16-Mark completion bonus.</span><div className="forage-status"><b>Attempts {attempts}/14</b><span>{matched.length/2}/8 pairs</span></div><div className="forage-grid forage-grid-4">{tiles.map((tile,index)=>{const isMatched=matched.includes(index);const shown=open.includes(index)||isMatched;return <button className={isMatched?'revealed matched':shown?'revealed':''} disabled={isMatched||earned!==null} onClick={()=>flip(index)} key={index} aria-label={shown?`${tile}${isMatched?' matched':''}`:`Hidden field sign ${index+1}`}>{shown?symbols[tile]:'?'}</button>})}</div>{earned!==null?<div className="forage-result"><h3>{matched.length===16?'Route cleared':'Contract ended'}</h3><p>You earned {earned} Marks.</p><button className="primary" onClick={collect}><Coins/> Collect Marks</button></div>:<small>Three contracts are available per account each day.</small>}</div></div>}
