import type {GameState,GardenPlot} from '../types';import {activeCreature} from '../game';import {seedById} from './gardenData';
const dayKey=(now:number)=>new Date(now).toISOString().slice(0,10);const hash=(value:string)=>[...value].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7);
export function hydrateGardenState(state:GameState,now=Date.now()):GameState{const today=dayKey(now),weather=state.gardenWeatherDate===today?state.gardenWeather:(['mild','rain','sun'] as const)[hash(`${today}-${state.player}`)%3];return {...state,gardenPlots:Array.from({length:4},(_,id)=>state.gardenPlots?.find(plot=>plot.id===id)??{id}),seeds:{mossberry:3,...(state.seeds??{})},discoveredSeeds:[...new Set(['mossberry',...(state.discoveredSeeds??[])])],gardenWeatherDate:today,gardenWeather:weather,gardenAssistDate:state.gardenAssistDate??''}}
export function seedUnlocked(state:GameState,id:string){return id==='mossberry'||id==='sunpetal'||(id==='cloudreed'&&state.creatures.some(c=>c.species==='galecrest'))||(id==='amberroot'&&state.creatures.some(c=>c.species==='cragback'))||(id==='glassbloom'&&state.glassrootStoryStep>0)||(id==='pearlfern'&&state.discoveredMaterials.includes('rootpearl'))}
export function growTime(state:GameState,plot:GardenPlot){const seed=plot.seedId&&seedById[plot.seedId];if(!seed)return 0;let factor=1;if(plot.wateredAt)factor-=.2;if(plot.assisted)factor-=.15;if(state.gardenWeather==='rain')factor-=.1;if(state.gardenWeather==='sun'&&seed.id==='sunpetal')factor-=.1;return Math.max(seed.growMs*.5,seed.growMs*factor)}
export function gardenProgress(state:GameState,plot:GardenPlot,now=Date.now()){if(!plot.seedId||!plot.plantedAt)return 0;return Math.max(0,Math.min(1,(now-plot.plantedAt)/growTime(state,plot)))}
export function plantSeed(state:GameState,plotId:number,seedId:string,now=Date.now()):GameState{const fresh=hydrateGardenState(state,now),plot=fresh.gardenPlots.find(p=>p.id===plotId);if(!plot||plot.seedId)return {...fresh,lastAction:'That garden plot is already in use.'};if(!seedById[seedId]||!seedUnlocked(fresh,seedId))return {...fresh,lastAction:'That seed has not been discovered yet.'};if((fresh.seeds[seedId]??0)<1)return {...fresh,lastAction:'No seeds of that variety remain. Harvest or gather more first.'};return {...fresh,seeds:{...fresh.seeds,[seedId]:fresh.seeds[seedId]-1},discoveredSeeds:[...new Set([...fresh.discoveredSeeds,seedId])],gardenPlots:fresh.gardenPlots.map(p=>p.id===plotId?{id:plotId,seedId,plantedAt:now}:p),lastAction:`${seedById[seedId].name} planted. It will never wither.`}}
export function waterPlot(state:GameState,plotId:number,now=Date.now()):GameState{const fresh=hydrateGardenState(state,now),plot=fresh.gardenPlots.find(p=>p.id===plotId);if(!plot?.seedId)return {...fresh,lastAction:'Plant a seed before watering this plot.'};if(plot.wateredAt)return {...fresh,lastAction:'This plot is already watered.'};return {...fresh,gardenPlots:fresh.gardenPlots.map(p=>p.id===plotId?{...p,wateredAt:now}:p),lastAction:'The soil is evenly watered. Growth time reduced.'}}
export function assistGarden(state:GameState,plotId:number,now=Date.now()):GameState{const fresh=hydrateGardenState(state,now),today=dayKey(now),plot=fresh.gardenPlots.find(p=>p.id===plotId),companion=activeCreature(fresh);if(fresh.gardenAssistDate===today)return {...fresh,lastAction:'Your companion has already helped in the garden today.'};if(!plot?.seedId)return {...fresh,lastAction:'Choose a planted plot for creature assistance.'};return {...fresh,gardenAssistDate:today,gardenPlots:fresh.gardenPlots.map(p=>p.id===plotId?{...p,assisted:true}:p),lastAction:`${companion.name} tended the plot. Growth time reduced.`}}
export function harvestPlot(state:GameState,plotId:number,now=Date.now()):GameState{const fresh=hydrateGardenState(state,now),plot=fresh.gardenPlots.find(p=>p.id===plotId);if(!plot?.seedId||gardenProgress(fresh,plot,now)<1)return {...fresh,lastAction:'This plant is still growing.'};const seed=seedById[plot.seedId],materials={...fresh.materials};if(seed.reward.material)materials[seed.reward.material]=(materials[seed.reward.material]??0)+seed.reward.quantity;return {...fresh,seeds:{...fresh.seeds,[seed.id]:(fresh.seeds[seed.id]??0)+1},materials,discoveredMaterials:seed.reward.material?[...new Set([...fresh.discoveredMaterials,seed.reward.material])]:fresh.discoveredMaterials,dewdrops:fresh.dewdrops+(seed.reward.marks??0),gardenPlots:fresh.gardenPlots.map(p=>p.id===plotId?{id:plotId}:p),lastAction:`${seed.name} harvested. One seed was saved for replanting.`}}
