import {useState} from 'react';
import {Award,BookOpen,Check,Feather,History,Leaf,Lock,Map,RotateCcw,Sparkles} from 'lucide-react';
import type {GameState} from '../types';
import {materials,recipes} from '../crafting/craftingData';
import {achievementDefinitions,claimAchievement,journalSummary,rewardLabel} from './journalEngine';
import {regions,speciesEntries} from './journalData';

const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;
type Tab='overview'|'creatures'|'regions'|'discoveries'|'achievements'|'history';
export function FieldJournalPage({state,act,reset}:{state:GameState;act:(state:GameState)=>void;reset:()=>void}){
 const[tab,setTab]=useState<Tab>('overview');const summary=journalSummary(state);const tabs:[Tab,string,typeof BookOpen][]=[['overview','Record',BookOpen],['creatures','Creatures',Feather],['regions','Regions',Map],['discoveries','Discoveries',Leaf],['achievements','Achievements',Award],['history','History',History]];
 return <section className="page field-journal-page"><header className="journal-hero"><div><p>Wanderer’s living field record</p><h1>{state.player}’s Journal</h1><span>Every trail, friendship, and discovery is recorded from your saved progression.</span></div><BookOpen aria-hidden="true"/></header>
  <nav className="journal-tabs" aria-label="Journal sections">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} aria-pressed={tab===id} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav>
  {tab==='overview'&&<><div className="journal-summary">{[['Creatures',summary.species.value,summary.species.total],['Regions',summary.regions.value,summary.regions.total],['Materials',summary.materials.value,summary.materials.total],['Recipes',summary.recipes.value,summary.recipes.total]].map(([label,value,total])=><article key={label}><b>{value}/{total}</b><span>{label}</span><progress value={Number(value)} max={Number(total)}/></article>)}<article><b>{summary.quests}</b><span>Quests claimed</span></article><article><b>{summary.bondMilestones}</b><span>Bond milestones</span></article></div><section className="journal-long-goal"><Sparkles/><div><h2>The complete Lumenwild record</h2><p>Chart every region, identify all eleven wild creatures, discover every regional material and recipe, and earn Gold in each achievement path.</p></div></section></>}
  {tab==='creatures'&&<div className="journal-species-grid">{speciesEntries.map(entry=>{const discovered=state.discoveries.includes(entry.id),owned=state.creatures.find(c=>c.species===entry.id);return <article key={entry.id} className={discovered?'':'hidden-entry'}><div className="journal-species-art"><img src={asset(entry.art)} alt={discovered?entry.name:'Undiscovered creature silhouette'}/>{!discovered&&<Lock/>}</div><small>{discovered?`${entry.rarity} · ${entry.temperament}`:'Entry obscured'}</small><h2>{discovered?entry.name:'Unknown species'}</h2><p>{discovered?<><b>Habitat:</b> {entry.habitat}</>:'Continue exploring; identity, habitat, and appearance remain hidden.'}</p>{discovered&&<p>{entry.lore}</p>}<span>{owned?`Befriended · Bond ${owned.bond}`:discovered?'Observed, not yet befriended':'No field notes yet'}</span></article>})}</div>}
  {tab==='regions'&&<div className="journal-region-grid">{regions.map(region=>{const complete=region.complete(state);const encounters=state.encounterHistory.filter(entry=>speciesEntries.find(s=>s.id===entry.species)?.habitat.includes(region.name.split(' ')[0])).length;return <article key={region.id} className={complete?'complete':''}><Map/><small>{complete?'Field record complete':'Survey in progress'}</small><h2>{region.name}</h2><p>{region.description}</p><span>{encounters} recorded approaches</span>{complete?<Check/>:<Lock/>}</article>})}</div>}
  {tab==='discoveries'&&<div className="discovery-ledger"><section><h2>Materials</h2>{materials.map(item=>{const known=state.discoveredMaterials.includes(item.id);return <article className={known?'':'unknown'} key={item.id}><i>{known?item.icon:'?'}</i><div><b>{known?item.name:'Unknown specimen'}</b><span>{known?`${item.rarity} · ${item.region}`:'Gather it to reveal this record.'}</span></div><strong>{state.materials[item.id]??0}</strong></article>})}</section><section><h2>Recipes</h2>{recipes.map(recipe=>{const known=state.discoveredRecipes.includes(recipe.id);return <article className={known?'':'unknown'} key={recipe.id}><i>{known?'✦':'?'}</i><div><b>{known?recipe.name:'Undiscovered recipe'}</b><span>{known?recipe.description:recipe.hint}</span></div>{known?<Check/>:<Lock/>}</article>})}</section></div>}
  {tab==='achievements'&&<div className="achievement-ledger">{achievementDefinitions.map(achievement=>{const value=achievement.value(state);return <article key={achievement.id}><header><div><small>{achievement.category}</small><h2>{achievement.title}</h2><p>{achievement.description}</p></div><b>{value}</b></header><div className="achievement-tiers">{achievement.tiers.map(tier=>{const earned=value>=tier.target,claimed=state.claimedAchievementTiers.includes(tier.id);return <div className={claimed?'claimed':earned?'earned':'locked'} key={tier.id}><span><b>{tier.label}</b><small>{Math.min(value,tier.target)}/{tier.target} · {rewardLabel(tier.reward)}</small></span>{claimed?<i><Check/> Claimed</i>:<button disabled={!earned} onClick={()=>act(claimAchievement(state,achievement.id,tier.id))}>{earned?'Claim reward':'Locked'}</button>}</div>})}</div></article>})}</div>}
  {tab==='history'&&<div className="journal-history"><section><h2>Encounter log</h2>{state.encounterHistory.length?<ol>{[...state.encounterHistory].reverse().map(entry=>{const species=speciesEntries.find(s=>s.id===entry.species);return <li key={entry.id}><span className={entry.result}/><div><b>{species?.name??entry.species}</b><small>{entry.region} · {new Date(entry.at).toLocaleDateString()}</small></div><strong>{entry.result==='success'?'Successful survey':'Approach missed'}</strong></li>})}</ol>:<p className="empty-state">No approaches recorded yet. Your next creature encounter will begin this history.</p>}</section><section><h2>Quest history</h2>{state.questHistory.length?<ol>{[...state.questHistory].reverse().map((id,index)=><li key={`${id}-${index}`}><Check/><div><b>{id.replace(/-/g,' ')}</b><small>Reward claimed and safely recorded</small></div></li>)}</ol>:<p className="empty-state">Claim a Quest Board reward to begin this history.</p>}</section></div>}
  <footer className="journal-account"><div><b>Account tools</b><span>Starting over permanently deletes this saved journey after confirmation.</span></div><a href="https://github.com/hightechstl/Lumenwild/issues/new" target="_blank" rel="noreferrer">Send playtest feedback</a><button className="danger" onClick={()=>{if(confirm('Delete this creature and restart your Lumenwild journey?'))reset()}}><RotateCcw/> Start over</button></footer>
 </section>
}
