import {useEffect,useMemo,useState} from 'react';
import {Home,Map,BookOpen,UserRound,House,Coins,Sparkles,ChevronRight,ArrowLeft,Gamepad2,Heart,Utensils,Brush,Palette,Gift,Check,RotateCcw,Cloud,LogOut,LoaderCircle} from 'lucide-react';
import {starters,shops} from './data'; import {buy,care,claimDaily,initialState,toggleEquip} from './game'; import type {GameState,Species} from './types';
import {AuthScreen} from './AuthScreen';
import {deleteGameState, observeAccount, saveGameState, signOutAccount, watchGameState} from './firebase';
import type {User} from 'firebase/auth';
const nav=[['home','Home',Home],['explore','Explore',Map],['nook','Nook',House],['collection','Collection',BookOpen],['profile','Profile',UserRound]] as const;
const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;
function Mark(){return <div className="mark"><span>✦</span>Lumenwild</div>}
function Landing({start}:{start:()=>void}){return <main className="landing"><header><Mark/><button className="quiet" onClick={start}>I’ve visited before</button></header><section className="hero"><div><h1>Build a life<br/>beyond the trail.</h1><p>Raise a creature, establish a home among the floating wilds, and take on new quests across an evolving frontier.</p><button className="primary" onClick={start}>Begin your journey <ChevronRight/></button><small>Free to play · No loot boxes · Progress saved across devices</small></div><div className="hero-art"><div className="sun"/><img src={asset('starters.png')} alt="Three original Lumenwild creatures"/></div></section><footer>Explore at your own pace. Return whenever the trail calls.</footer></main>}
function Onboarding({finish}:{finish:(s:GameState)=>void}){const[step,setStep]=useState(0);const[species,setSpecies]=useState<Species>('spriggle');const[name,setName]=useState('Pip');return <main className="onboard"><header><Mark/><span>Creature selection · {step+1} of 2</span></header>{step===0?<section><h1>Choose your first creature</h1><p>Each species has a different temperament and field ability.</p><div className="starter-grid">{starters.map((x,i)=><button className={species===x.id?'starter selected':'starter'} onClick={()=>setSpecies(x.id)} key={x.id}><div className={`sprite crop-${i}`}><img src={asset(`${x.id}.png`)} alt=""/></div><h2>{x.name}</h2><b>{x.temperament}</b><small>{x.gift}</small>{species===x.id&&<i><Check/> Selected</i>}</button>)}</div><button className="primary" onClick={()=>setStep(1)}>Choose this creature <ChevronRight/></button></section>:<section className="name-step"><button className="back" onClick={()=>setStep(0)}><ArrowLeft/> Back</button><div className={`solo crop-${starters.findIndex(x=>x.id===species)}`}><img src={asset(`${species}.png`)} alt="Your chosen creature"/></div><h1>Name your new companion</h1><label>What will you call your {starters.find(x=>x.id===species)?.name}?<input value={name} maxLength={14} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={!name.trim()} onClick={()=>finish(initialState(species,name.trim()))}>Enter Lumenwild <ChevronRight/></button></section>}</main>}
const needMeta={hunger:['Hunger',Utensils],mood:['Mood',Sparkles],energy:['Energy',Sparkles],health:['Health',Heart],bond:['Bond',Heart]} as const;
const itemCells:Record<string,[number,number]>={tart:[0,0],bell:[1,0],primer:[2,0],beret:[0,1],lamp:[1,1],tea:[2,1]};
function ItemArt({id}:{id:string}){const cell=itemCells[id]??[0,0];return <span className="item-art" style={{backgroundImage:`url(${asset('items.png')})`,backgroundPosition:`${cell[0]*50}% ${cell[1]*100}%`}} aria-hidden="true"/>}
const wildCreatures=[['Mosskit','Mossmere','Forager',0,0],['Galecrest','Cloudfen','Wind scout',1,0],['Cragback','Amber Reach','Armored grazer',2,0],['Emberstride','Amber Reach','Ridge runner',0,1],['Veilfin','Cloudfen','Sky drifter',1,1],['Old Warden','The Ruins','Guardian',2,1]] as const;
function WildCreature({entry}:{entry:typeof wildCreatures[number]}){return <article className="field-creature"><span className="wild-art" style={{backgroundImage:`url(${asset('creature-roster.png')})`,backgroundPosition:`${entry[3]*50}% ${entry[4]*100}%`}}/><div><small>{entry[1]} · {entry[2]}</small><h3>{entry[0]}</h3></div></article>}
function Shell({state,setState,onReset,email}:{state:GameState;setState:(s:GameState)=>void;onReset:()=>void;email:string}){const[screen,setScreen]=useState('home');const[toasts,setToast]=useState('');const act=(next:GameState)=>{setState(next);setToast(next.lastAction);setTimeout(()=>setToast(''),1700)};return <div className="app-shell"><aside><Mark/><nav>{nav.map(([id,label,Icon])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><Icon/>{label}</button>)}</nav><div className="aside-bottom"><span><Coins/> {state.dewdrops.toLocaleString()}</span><span><Sparkles/> {state.starpetals}</span><span className="cloud-saved"><Cloud/> Cloud saved</span><small>{email}</small><button className="sign-out" onClick={()=>void signOutAccount()}><LogOut/> Sign out</button></div></aside><header className="mobile-head"><Mark/><div><Cloud/> Saved</div></header><main className="content">{screen==='home'&&<HomeScreen state={state} act={act} go={setScreen}/>} {screen==='explore'&&<Explore state={state} act={act}/>} {screen==='nook'&&<Nook state={state} act={act}/>} {screen==='collection'&&<Collection state={state} act={act}/>} {screen==='profile'&&<Profile state={state} reset={onReset}/>}</main><nav className="mobile-nav">{nav.map(([id,label,Icon])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><Icon/><small>{label}</small></button>)}</nav>{toasts&&<div className="toast">✦ {toasts}</div>}</div>}
function Creature({state,small=false}:{state:GameState;small?:boolean}){const idx=starters.findIndex(x=>x.id===state.species);return <div className={`${small?'creature small':'creature'} crop-${idx}`}><img src={asset(`${state.species}.png`)} alt={`${state.creatureName}, a ${state.species}`}/>{state.equipped.includes('beret')&&<span className="hat">🌰</span>}</div>}
function HomeScreen({state,act,go}:{state:GameState;act:(s:GameState)=>void;go:(x:string)=>void}){return <div className="home-screen"><div className="scene"><div className="scene-top"><div><p>Base camp · Mossmere</p><h1>{state.creatureName}</h1></div><div className="wallet"><span><Coins/> {state.dewdrops.toLocaleString()} <small>Dewdrops</small></span><span><Sparkles/> {state.starpetals} <small>Starpetals</small></span></div></div><div className="habitat" style={{backgroundImage:`url(${asset('mossmere-habitat.png')})`}}><div className="window">☁︎</div><div className="shelf">✦　▥　⌂</div><Creature state={state}/><div className="plant">♧</div><div className="rug"/></div><div className="needs">{Object.entries(state.needs).map(([key,val])=>{const [label,Icon]=needMeta[key as keyof typeof needMeta];return <div key={key}><span><Icon/> {label}<b>{val}</b></span><i><em style={{width:`${val}%`}}/></i></div>})}</div><div className="care"><button onClick={()=>act(care(state,'feed'))}><Utensils/>Feed</button><button onClick={()=>act(care(state,'groom'))}><Brush/>Groom</button><button onClick={()=>act(care(state,'play'))}><Gamepad2/>Train</button><button onClick={()=>act(care(state,'read'))}><BookOpen/>Study</button></div></div><aside className="today"><div className="daily"><Gift/><p>Daily quest</p><h2>Field Routine</h2><span>Complete 3 care actions</span><div className="progress"><i style={{width:`${state.dailyCare/3*100}%`}}/></div><b>{state.dailyCare}/3</b><button disabled={state.dailyCare<3||state.claimed} onClick={()=>act(claimDaily(state))}>{state.claimed?'Completed':'Complete quest · 100 Dewdrops'}</button></div><h3>Inventory</h3>{state.inventory.filter(x=>x.quantity>0).slice(0,4).map(item=><button className="item-row" key={item.id} onClick={()=>go('collection')}><span>{item.icon}</span><div>{item.name}<small>{item.category}</small></div><b>{item.quantity}</b></button>)}<div className="destinations"><button className="region-card" onClick={()=>go('explore')}><span>Destination</span><b>Mossmere</b><ChevronRight/></button><button className="region-card skyhop-card" onClick={()=>go('explore')}><span>Challenge</span><b>Skyhop</b><Gamepad2/></button></div></aside></div>}
function Explore({state,act}:{state:GameState;act:(s:GameState)=>void}){const[shop,setShop]=useState(0);const[game,setGame]=useState(false);return <section className="page explore"><header><p>The Bramblewake Archipelago</p><h1>Explore the frontier</h1><span>Chart regions, meet wild creatures, and prepare for the trails ahead.</span></header><div className="map-art illustrated-map" style={{backgroundImage:`url(${asset('bramblewake-map.png')})`}}><button className="map-marker mossmere"><b>Mossmere</b><small>Base camp · Open</small></button><button className="map-marker cloudfen"><b>Cloudfen</b><small>Skyhop · Open</small></button><button className="map-marker amber"><b>Amber Reach</b><small>Requires 3 quests</small></button><button className="skyhop-launch" onClick={()=>setGame(true)}><Gamepad2/> Play Skyhop</button></div>{game&&<Skyhop close={()=>setGame(false)} reward={n=>act({...state,dewdrops:state.dewdrops+n,lastAction:`Skyhop reward: +${n} Dewdrops!`})}/>}<section className="encounters"><div><p>Field encounters</p><h2>Creatures of Bramblewake</h2></div><div className="creature-rail">{wildCreatures.map(entry=><WildCreature key={entry[0]} entry={entry}/>)}</div></section><div className="shops"><div className="shop-tabs">{shops.map((s,i)=><button className={i===shop?'active':''} onClick={()=>setShop(i)} key={s.name}>{s.name}</button>)}</div><h2>{shops[shop].name}</h2><p><b>{shops[shop].keeper}</b> · “{shops[shop].line}”</p><div className="wares">{shops[shop].items.map(id=>{const it=state.inventory.find(x=>x.id===id)!;return <article key={id}><ItemArt id={id}/><h3>{it.name}</h3><p>{it.description}</p><button onClick={()=>act(buy(state,id))}><Coins/> {it.price}</button></article>})}</div></div></section>}
function Collection({state,act}:{state:GameState;act:(s:GameState)=>void}){return <section className="page collection-page"><header><p>Field inventory</p><h1>Your collection</h1><span>{state.inventory.reduce((n,x)=>n+x.quantity,0)} objects gathered across Bramblewake.</span></header><div className="inventory-grid">{state.inventory.map(it=><article className={it.quantity?'':'locked'} key={it.id}><ItemArt id={it.id}/><div><small>{it.category}</small><h3>{it.name}</h3><p>{it.description}</p></div><b>× {it.quantity}</b>{it.category==='wearable'&&it.quantity>0&&<button onClick={()=>act(toggleEquip(state,it.id))}>{state.equipped.includes(it.id)?'Unequip':'Equip'}</button>}</article>)}</div></section>}
function Nook({state,act}:{state:GameState;act:(s:GameState)=>void}){const themes=[['Mossy Hollow','nook-mossy-hollow.png'],['Sunwashed Loft','nook-sunwashed-loft.png'],['Moonlit Burrow','nook-moonlit-burrow.png']] as const;const current=themes.find(x=>x[0]===state.roomTheme)??themes[0];return <section className="page nook-page"><header><p>Companion quarters</p><h1>{state.creatureName}’s nook</h1><span>Choose a room and arrange the equipment you have collected.</span></header><div className="nook-preview illustrated-room" style={{backgroundImage:`url(${asset(current[1])})`}}><div className="room-weather"/><Creature state={state}/>{state.inventory.find(x=>x.id==='lamp')?.quantity?<ItemArt id="lamp"/>:null}<ItemArt id="primer"/></div><div className="theme-picks">{themes.map(([name])=><button className={state.roomTheme===name?'active':''} onClick={()=>act({...state,roomTheme:name,lastAction:`The nook is now ${name}.`})} key={name}><Palette/>{name}</button>)}</div></section>}
function Profile({state,reset}:{state:GameState;reset:()=>void}){const routineComplete=state.achievements.includes('Field Routine')||state.achievements.includes('A Little Brighter');return <section className="page profile field-journal"><header><p>Wanderer’s field record</p><h1>Expedition journal</h1></header><div className="journal-grid"><div className="profile-lead"><Creature state={state} small/><div><small>Field operator</small><h2>{state.player}</h2><p>Companion to {state.creatureName} · Based in Mossmere</p></div></div><div className="record-stats"><article><b>{state.dailyCare}</b><span>Care actions</span></article><article><b>1/3</b><span>Regions charted</span></article><article><b>{state.inventory.filter(i=>i.quantity).length}/6</b><span>Items found</span></article><article><b>6</b><span>Creatures sighted</span></article></div></div><section className="journal-regions"><h2>Region notes</h2><div><article><b>Mossmere</b><span>Base camp established</span></article><article><b>Cloudfen</b><span>Sky routes surveyed</span></article><article className="locked"><b>Amber Reach</b><span>Expedition locked</span></article></div></section><h2>Achievements</h2><div className="achievement-list"><article><span>✦</span><div><h3>First Companion</h3><p>Adopt your first creature.</p></div><Check/></article><article className={routineComplete?'':'dim'}><span>☀</span><div><h3>Field Routine</h3><p>Complete a daily quest.</p></div>{routineComplete?<Check/>:<small>In progress</small>}</article></div><div className="profile-actions"><button className="sign-out" onClick={()=>void signOutAccount()}><LogOut/> Sign out</button><button className="danger" onClick={()=>{if(confirm('Delete this creature and restart your Lumenwild journey?'))reset()}}><RotateCcw/> Start over</button></div></section>}
function Skyhop({close,reward}:{close:()=>void;reward:(n:number)=>void}){const[lane,setLane]=useState(1);const[round,setRound]=useState(0);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const cloud=useMemo(()=>[0,2,1,0,2,2,1,0][round%8],[round]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setLane(x=>Math.max(0,x-1));if(e.key==='ArrowRight')setLane(x=>Math.min(2,x+1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);const hop=()=>{if(done)return;const hit=lane===cloud;const next=round+1;setScore(x=>x+(hit?2:1));if(next===8){setDone(true);reward(Math.min(60,(score+(hit?2:1))*4))}else setRound(next)};return <div className="modal-back"><div className="game-modal" role="dialog" aria-modal="true" aria-label="Skyhop minigame"><button className="close" onClick={close}>×</button><p>Cloudfen pastime</p><h2>Skyhop</h2><span>Choose a lane, then hop. Land on the bright cloud for a bonus.</span><div className="sky-game"><div className="cloud-row">{[0,1,2].map(x=><i className={x===cloud?'bright':''} key={x}>☁</i>)}</div><div className="hopper" style={{left:`${lane*33.33+16.66}%`}}>✦</div></div>{done?<><h3>Trail complete · {score} points</h3><button className="primary" onClick={close}>Collect reward</button></>:<><div className="lane-controls"><button onClick={()=>setLane(x=>Math.max(0,x-1))}>← Left</button><button onClick={hop}>Hop {round+1}/8</button><button onClick={()=>setLane(x=>Math.min(2,x+1))}>Right →</button></div><small>Keyboard: ← → to move</small></>}</div></div>}
function CloudLoading({message='Opening your field journal…'}:{message?:string}){return <main className="cloud-loading"><Mark/><LoaderCircle className="spin"/><h1>{message}</h1><p>Your Lumenwild is syncing securely with Firebase.</p></main>}
function DevelopmentPreview(){const[state,setState]=useState(()=>initialState());return <Shell state={state} setState={setState} email="Development preview" onReset={()=>setState(initialState())}/>}

export function App(){
  const[user,setUser]=useState<User|null|undefined>(undefined);
  const[saved,setSaved]=useState<GameState|null>(null);
  const[loadingGame,setLoadingGame]=useState(true);
  const[cloudError,setCloudError]=useState('');

  useEffect(()=>observeAccount((account)=>{setUser(account);if(!account){setSaved(null);setLoadingGame(false)}}),[]);
  useEffect(()=>{
    if(!user)return;
    setLoadingGame(true);
    return watchGameState(user.uid,(state)=>{setSaved(state);setLoadingGame(false);setCloudError('')},()=>{setCloudError('We could not load your Firebase save. Check Firestore setup and try again.');setLoadingGame(false)});
  },[user]);

  if(import.meta.env.DEV&&new URLSearchParams(location.search).has('preview'))return <DevelopmentPreview/>;

  if(user===undefined)return <CloudLoading message="Finding your account…"/>;
  if(user===null)return <AuthScreen/>;
  if(loadingGame)return <CloudLoading/>;
  if(cloudError)return <main className="cloud-loading"><Mark/><h1>Clouds on the trail</h1><p>{cloudError}</p><button className="primary" onClick={()=>location.reload()}>Try again</button></main>;

  const commit=(next:GameState)=>{setSaved(next);void saveGameState(user.uid,next).catch(()=>setCloudError('Your latest change could not be saved. Please reconnect and try again.'))};
  const finish=(state:GameState)=>commit({...state,player:user.displayName||'Wanderer'});
  if(!saved)return <Onboarding finish={finish}/>;
  return <Shell state={saved} setState={commit} email={user.email||'Firebase account'} onReset={()=>{void deleteGameState(user.uid);setSaved(null)}}/>;
}
