import {describe,expect,it} from 'vitest';
import {CURRENT_SCHEMA_VERSION,migrateGameState} from './firebase';
import {initialState} from './game';

describe('Firebase save migrations',()=>{
  it('preserves economy, inventory, and identity while adding quest and crafting metadata',()=>{const old={...initialState(),player:'Returning Wanderer',dewdrops:777,saveRevision:undefined,recentActions:undefined,materials:undefined,discoveredMaterials:undefined,discoveredRecipes:undefined,cosmetics:undefined,questRecords:undefined,questHistory:undefined} as unknown as ReturnType<typeof initialState>;const migrated=migrateGameState(old);expect(migrated.player).toBe('Returning Wanderer');expect(migrated.dewdrops).toBe(777);expect(migrated.saveRevision).toBe(0);expect(migrated.recentActions).toEqual([]);expect(migrated.materials).toEqual({});expect(migrated.discoveredRecipes).toEqual(expect.arrayContaining(['trail-kit','mossberry-offering']));expect(migrated.inventory.find(item=>item.id==='trail-kit')?.quantity).toBe(0);expect(Object.keys(migrated.questRecords).length).toBeGreaterThan(0);expect(CURRENT_SCHEMA_VERSION).toBe(10)});
  it('preserves crafted quantities and existing regional materials through schema 10',()=>{const base=initialState();const old={...base,materials:{mossfiber:9},inventory:base.inventory.map(item=>item.id==='trail-kit'?{...item,quantity:4}:item)};const migrated=migrateGameState(old);expect(migrated.materials.mossfiber).toBe(9);expect(migrated.inventory.find(item=>item.id==='trail-kit')?.quantity).toBe(4);expect(migrated.discoveredMaterials).toContain('mossfiber')});
  it('normalizes renamed achievements without duplicating them',()=>{const migrated=migrateGameState({...initialState(),achievements:['First Light','First Companion','A Little Brighter']});expect(migrated.achievements).toEqual(['First Companion','Field Routine'])});
  it('retains only the latest action receipts',()=>{const recentActions=Array.from({length:40},(_,i)=>`action-${i}`);expect(migrateGameState({...initialState(),recentActions}).recentActions).toEqual(recentActions.slice(-30))});
});
