import type { GameState, NeedKey, OwnedCreature, Species, WildSpecies } from './types'; import { seedItems } from './data';
export const starterCreature=(species:Species,name:string,bond=81):OwnedCreature=>({id:'starter',species,name,rarity:'Common',bond,origin:'First companion'});
export const initialState=(species:Species='spriggle',name='Pip'):GameState=>({player:'Wanderer',creatureName:name,species,needs:{hunger:72,mood:88,energy:64,health:95,bond:81},dewdrops:1240,starpetals:12,inventory:seedItems.map(x=>({...x})),equipped:[],roomTheme:'Mossy Hollow',dailyCare:0,claimed:false,achievements:['First Light'],lastAction:'Welcome home.',creatures:[starterCreature(species,name)],activeCreatureId:'starter',discoveries:['mosskit'],encounterProgress:{mosskit:0}});
export const activeCreature=(s:GameState)=>s.creatures.find(x=>x.id===s.activeCreatureId)??s.creatures[0]??starterCreature(s.species,s.creatureName,s.needs.bond);
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export function care(s:GameState,action:'feed'|'groom'|'play'|'read'):GameState{const effects:Record<typeof action,Partial<Record<NeedKey,number>>>={feed:{hunger:15,health:2},groom:{health:5,bond:5},play:{mood:12,energy:-5,bond:4},read:{mood:6,energy:5,bond:6}}; const needs={...s.needs}; Object.entries(effects[action]).forEach(([k,v])=>needs[k as NeedKey]=clamp(needs[k as NeedKey]+v!)); const active=activeCreature(s);return {...s,needs,creatures:s.creatures.map(x=>x.id===active.id?{...x,bond:needs.bond}:x),dailyCare:Math.min(3,s.dailyCare+1),lastAction:`${active.name} responded well.`};}
export function buy(s:GameState,id:string):GameState{const item=s.inventory.find(i=>i.id===id); if(!item||s.dewdrops<item.price)return {...s,lastAction:'Not enough Marks yet.'}; return {...s,dewdrops:s.dewdrops-item.price,inventory:s.inventory.map(i=>i.id===id?{...i,quantity:i.quantity+1}:i),lastAction:`Added ${item.name} to your satchel.`};}
export function toggleEquip(s:GameState,id:string):GameState{const owned=s.inventory.find(i=>i.id===id&&i.quantity>0); if(!owned)return s; const equipped=s.equipped.includes(id)?s.equipped.filter(x=>x!==id):[...s.equipped.filter(x=>x!=='beret'),id]; return {...s,equipped,lastAction:s.equipped.includes(id)?'Tucked away safely.':`${owned.name} equipped!`};}
export function claimDaily(s:GameState):GameState{return s.dailyCare>=3&&!s.claimed?{...s,claimed:true,dewdrops:s.dewdrops+100,achievements:[...new Set([...s.achievements,'Field Routine'])],lastAction:'Daily quest complete: +100 Marks!'}:s}
export function studyEncounter(s:GameState,species:WildSpecies):GameState{if(s.creatures.some(x=>x.species===species))return s;if(s.needs.energy<12)return {...s,lastAction:'Your companion needs at least 12 Energy to survey safely.'};const progress=Math.min(3,(s.encounterProgress[species]??0)+1);return {...s,needs:{...s.needs,energy:s.needs.energy-12},discoveries:[...new Set([...s.discoveries,species])],encounterProgress:{...s.encounterProgress,[species]:progress},lastAction:progress===3?'Mosskit trusts your approach. Gather the offering and permit fee.':`Survey complete: Mosskit trust ${progress}/3. Energy -12.`}}
export function missEncounter(s:GameState):GameState{if(s.needs.energy<12)return {...s,lastAction:'Your companion needs at least 12 Energy to survey safely.'};return {...s,needs:{...s.needs,energy:s.needs.energy-12},lastAction:'The trail went cold. Energy -12; no trust gained.'}}
export function befriendMosskit(s:GameState):GameState{if((s.encounterProgress.mosskit??0)<3||s.creatures.some(x=>x.species==='mosskit'))return s;const tart=s.inventory.find(x=>x.id==='tart');if(!tart?.quantity)return {...s,lastAction:'A Mossberry Tart is required as an offering.'};if(s.dewdrops<250)return {...s,lastAction:'The Mossmere permit requires 250 Marks.'};const mosskit:OwnedCreature={id:'mosskit-1',species:'mosskit',name:'Mosskit',rarity:'Uncommon',bond:35,origin:'Befriended in Mossmere'};return {...s,dewdrops:s.dewdrops-250,inventory:s.inventory.map(x=>x.id==='tart'?{...x,quantity:x.quantity-1}:x),creatures:[...s.creatures,mosskit],achievements:[...new Set([...s.achievements,'Field Naturalist'])],lastAction:'Mosskit joined your roster. Offering accepted; permit registered.'}}
export function selectCreature(s:GameState,id:string):GameState{const creature=s.creatures.find(x=>x.id===id);return creature?{...s,activeCreatureId:id,lastAction:`${creature.name} is now your active companion.`}:s}
