import type { CreatureStats, GameState, NeedKey, OwnedCreature, Species, WildSpecies } from './types'; import { seedItems } from './data';
export const ENERGY_REGEN_MS=5*60*1000;
const starterStats:Record<Species,CreatureStats>={spriggle:{tracking:68,agility:58,resolve:48},mallowisp:{tracking:52,agility:44,resolve:72},bramblet:{tracking:45,agility:55,resolve:76}};
export const starterCreature=(species:Species,name:string,bond=81):OwnedCreature=>({id:'starter',species,name,rarity:'Common',bond,origin:'First companion',stats:starterStats[species],energy:64,maxEnergy:100,energyUpdatedAt:Date.now()});
export function recoverCreature(creature:OwnedCreature,now=Date.now()):OwnedCreature{const elapsed=Math.max(0,now-(creature.energyUpdatedAt||now));const gained=Math.floor(elapsed/ENERGY_REGEN_MS);if(!gained||creature.energy>=creature.maxEnergy)return creature;return {...creature,energy:Math.min(creature.maxEnergy,creature.energy+gained),energyUpdatedAt:(creature.energyUpdatedAt||now)+gained*ENERGY_REGEN_MS}}
const dayKey=(now=Date.now())=>new Date(now).toISOString().slice(0,10);
const encounterOrder:WildSpecies[]=['mosskit','galecrest','cragback','emberstride','veilfin','old-warden'];
const hash=(value:string)=>[...value].reduce((total,char)=>((total*31+char.charCodeAt(0))>>>0),2166136261);
export function refreshExpeditionState(s:GameState,now=Date.now()):GameState{const today=dayKey(now);const fieldDays=[...new Set([...(s.fieldDays??[]),today])];const rank=fieldDays.length;const eligible=encounterOrder.filter(species=>species==='mosskit'||species==='galecrest'||species==='cragback'||(species==='emberstride'&&rank>=4)||(species==='veilfin'&&rank>=5)||(species==='old-warden'&&rank>=7));const rotation=s.encounterRotationDate===today&&s.encounterRotation?.length?s.encounterRotation:[...eligible].sort((a,b)=>hash(`${today}-${s.player}-${a}`)-hash(`${today}-${s.player}-${b}`)).slice(0,rank<4?2:3);const sameCareDay=s.dailyCareDate===today;return {...s,dailyCare:sameCareDay?s.dailyCare:0,dailyCareDate:today,claimed:sameCareDay?s.claimed:false,fieldDays,encounterRotationDate:today,encounterRotation:rotation,encounterAttemptDate:today,dailyEncounterAttempts:s.encounterAttemptDate===today?(s.dailyEncounterAttempts??{}):{}}}
export function recoverState(s:GameState,now=Date.now()):GameState{const creatures=s.creatures.map(x=>recoverCreature(x,now));const active=creatures.find(x=>x.id===s.activeCreatureId)??creatures[0];return refreshExpeditionState({...s,creatures,needs:{...s.needs,energy:active?.energy??s.needs.energy}},now)}
export const initialState=(species:Species='spriggle',name='Pip'):GameState=>refreshExpeditionState({saveRevision:0,recentActions:[],player:'Wanderer',creatureName:name,species,needs:{hunger:72,mood:88,energy:64,health:95,bond:81},dewdrops:250,starpetals:12,inventory:seedItems.map(x=>({...x})),equipped:[],roomTheme:'Mossy Hollow',dailyCare:0,dailyCareDate:'',claimed:false,achievements:['First Light'],lastAction:'Welcome home.',creatures:[starterCreature(species,name)],activeCreatureId:'starter',discoveries:['mosskit'],encounterProgress:{mosskit:0},encounterDays:{},encounterRotationDate:'',encounterRotation:[],encounterAttemptDate:'',dailyEncounterAttempts:{},fieldDays:[],forageDate:'',foragePlays:0});
export const activeCreature=(s:GameState)=>s.creatures.find(x=>x.id===s.activeCreatureId)??s.creatures[0]??starterCreature(s.species,s.creatureName,s.needs.bond);
export function encounterTuning(s:GameState,species:WildSpecies){const creature=activeCreature(s);const attribute=species==='mosskit'||species==='veilfin'?'tracking':species==='galecrest'||species==='emberstride'?'agility':'resolve';const requirements:Record<WildSpecies,number>={mosskit:48,galecrest:68,cragback:78,emberstride:82,veilfin:86,'old-warden':92};const requirement=requirements[species];const score=creature.stats[attribute];const delta=score-requirement;return {attribute,score,requirement,windowPct:Math.max(14,Math.min(36,26+delta*.3)),step:Math.max(.9,Math.min(2.8,1.8-delta*.022))}}
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export function care(s:GameState,action:'feed'|'groom'|'play'|'read',now=Date.now()):GameState{const fresh=refreshExpeditionState(s,now);const effects:Record<typeof action,Partial<Record<NeedKey,number>>>={feed:{hunger:15,health:2},groom:{health:5,bond:5},play:{mood:12,energy:-5,bond:4},read:{mood:6,bond:6}};const active=activeCreature(fresh);const needs={...fresh.needs,energy:active.energy};Object.entries(effects[action]).forEach(([k,v])=>needs[k as NeedKey]=clamp(needs[k as NeedKey]+v!));return {...fresh,needs,creatures:fresh.creatures.map(x=>x.id===active.id?{...x,bond:needs.bond,energy:needs.energy,energyUpdatedAt:now}:x),dailyCare:Math.min(3,fresh.dailyCare+1),lastAction:`${active.name} responded well.`};}
export function buy(s:GameState,id:string):GameState{const item=s.inventory.find(i=>i.id===id); if(!item||s.dewdrops<item.price)return {...s,lastAction:'Not enough Marks yet.'}; return {...s,dewdrops:s.dewdrops-item.price,inventory:s.inventory.map(i=>i.id===id?{...i,quantity:i.quantity+1}:i),lastAction:`Added ${item.name} to your satchel.`};}
export function toggleEquip(s:GameState,id:string):GameState{const owned=s.inventory.find(i=>i.id===id&&i.quantity>0); if(!owned)return s; const equipped=s.equipped.includes(id)?s.equipped.filter(x=>x!==id):[...s.equipped.filter(x=>x!=='beret'),id]; return {...s,equipped,lastAction:s.equipped.includes(id)?'Tucked away safely.':`${owned.name} equipped!`};}
export function claimDaily(s:GameState,now=Date.now()):GameState{const fresh=refreshExpeditionState(s,now);return fresh.dailyCare>=3&&!fresh.claimed?{...fresh,claimed:true,dewdrops:fresh.dewdrops+100,achievements:[...new Set([...fresh.achievements,'Field Routine'])],lastAction:'Daily quest complete: +100 Marks!'}:fresh}
export const encounterGoals:Record<WildSpecies,number>={mosskit:3,galecrest:4,cragback:5,emberstride:5,veilfin:6,'old-warden':7};
export function encounterAvailability(s:GameState,species:WildSpecies,now=Date.now()){const today=dayKey(now);const owned=s.creatures.some(x=>x.species===species);const available=s.encounterRotation.includes(species);const studied=(s.encounterDays[species]??[]).includes(today);const attempts=s.encounterAttemptDate===today?(s.dailyEncounterAttempts[species]??0):0;return {owned,available,studied,attempts,attemptsLeft:Math.max(0,3-attempts),canAttempt:!owned&&available&&!studied&&attempts<3}}
export function studyEncounter(s:GameState,species:WildSpecies,now=Date.now()):GameState{if(s.creatures.some(x=>x.species===species))return s;const fresh=refreshExpeditionState(s,now);const status=encounterAvailability(fresh,species,now);if(!status.available)return {...fresh,lastAction:'That trail is quiet today. Check tomorrow’s field sightings.'};if(status.studied)return {...fresh,lastAction:'Today’s field notes are complete. This creature needs time before trust can grow again.'};if(status.attempts>=3)return {...fresh,lastAction:'No safe approaches remain today. Return after the sightings rotate.'};const companion=activeCreature(fresh);if(companion.energy<12)return {...fresh,lastAction:`${companion.name} needs at least 12 Energy to survey safely.`};const names:Record<WildSpecies,string>={mosskit:'Mosskit',galecrest:'Galecrest',cragback:'Cragback',emberstride:'Emberstride',veilfin:'Veilfin','old-warden':'Old Warden'};const goal=encounterGoals[species],name=names[species];const progress=Math.min(goal,(fresh.encounterProgress[species]??0)+1);const energy=companion.energy-12;const today=dayKey(now);return {...fresh,needs:{...fresh.needs,energy},creatures:fresh.creatures.map(x=>x.id===companion.id?{...x,energy,energyUpdatedAt:now}:x),discoveries:[...new Set([...fresh.discoveries,species])],encounterProgress:{...fresh.encounterProgress,[species]:progress},encounterDays:{...fresh.encounterDays,[species]:[...new Set([...(fresh.encounterDays[species]??[]),today])]},dailyEncounterAttempts:{...fresh.dailyEncounterAttempts,[species]:(fresh.dailyEncounterAttempts[species]??0)+1},lastAction:progress===goal?`${name} trusts your approach. Gather the required supplies.`:`Field day recorded: ${name} trust ${progress}/${goal}. Return on another sighting day.`}}
export function missEncounter(s:GameState,species:WildSpecies='mosskit',now=Date.now()):GameState{const fresh=refreshExpeditionState(s,now);const status=encounterAvailability(fresh,species,now);if(!status.canAttempt)return {...fresh,lastAction:status.studied?'Today’s field notes are already complete.':'No safe approaches remain for this sighting today.'};const companion=activeCreature(fresh);if(companion.energy<12)return {...fresh,lastAction:`${companion.name} needs at least 12 Energy to survey safely.`};const energy=companion.energy-12;return {...fresh,needs:{...fresh.needs,energy},creatures:fresh.creatures.map(x=>x.id===companion.id?{...x,energy,energyUpdatedAt:now}:x),dailyEncounterAttempts:{...fresh.dailyEncounterAttempts,[species]:(fresh.dailyEncounterAttempts[species]??0)+1},lastAction:`The trail went cold. ${companion.name} Energy -12; ${Math.max(0,2-(fresh.dailyEncounterAttempts[species]??0))} safe approaches remain today.`}}
export function befriendMosskit(s:GameState):GameState{if((s.encounterProgress.mosskit??0)<3||s.creatures.some(x=>x.species==='mosskit'))return s;const tart=s.inventory.find(x=>x.id==='tart');if(!tart?.quantity)return {...s,lastAction:'A Mossberry Tart is required as an offering.'};if(s.dewdrops<250)return {...s,lastAction:'The Mossmere permit requires 250 Marks.'};const mosskit:OwnedCreature={id:'mosskit-1',species:'mosskit',name:'Mosskit',rarity:'Uncommon',bond:35,origin:'Befriended in Mossmere',stats:{tracking:82,agility:60,resolve:55},energy:100,maxEnergy:100,energyUpdatedAt:Date.now()};return {...s,dewdrops:s.dewdrops-250,inventory:s.inventory.map(x=>x.id==='tart'?{...x,quantity:x.quantity-1}:x),creatures:[...s.creatures,mosskit],discoveries:[...new Set<WildSpecies>([...s.discoveries,'galecrest'])],achievements:[...new Set([...s.achievements,'Field Naturalist'])],lastAction:'Mosskit joined your roster. Cloudfen and Galecrest encounters unlocked.'}}
export function befriendGalecrest(s:GameState):GameState{if((s.encounterProgress.galecrest??0)<4||s.creatures.some(x=>x.species==='galecrest'))return s;const tea=s.inventory.find(x=>x.id==='tea');if((tea?.quantity??0)<2)return {...s,lastAction:'Two Sunpetal Teas are required for the Cloudfen ascent.'};if(s.dewdrops<500)return {...s,lastAction:'The Cloudfen expedition requires 500 Marks.'};const galecrest:OwnedCreature={id:'galecrest-1',species:'galecrest',name:'Galecrest',rarity:'Rare',bond:25,origin:'Befriended in Cloudfen',stats:{tracking:55,agility:88,resolve:50},energy:100,maxEnergy:100,energyUpdatedAt:Date.now()};return {...s,dewdrops:s.dewdrops-500,inventory:s.inventory.map(x=>x.id==='tea'?{...x,quantity:x.quantity-2}:x),creatures:[...s.creatures,galecrest],discoveries:[...new Set<WildSpecies>([...s.discoveries,'cragback'])],achievements:[...new Set([...s.achievements,'Cloudfen Pathfinder'])],lastAction:'Galecrest joined your roster. Amber Reach scouting unlocked.'}}
export function befriendCragback(s:GameState):GameState{if((s.encounterProgress.cragback??0)<5||s.creatures.some(x=>x.species==='cragback'))return s;const primer=s.inventory.find(x=>x.id==='primer');if((primer?.quantity??0)<3)return {...s,lastAction:'Three Moonleaf Primers are required to chart the stone paths.'};if(s.dewdrops<750)return {...s,lastAction:'The Amber Reach expedition requires 750 Marks.'};const cragback:OwnedCreature={id:'cragback-1',species:'cragback',name:'Cragback',rarity:'Rare',bond:20,origin:'Befriended in Amber Reach',stats:{tracking:48,agility:35,resolve:92},energy:100,maxEnergy:100,energyUpdatedAt:Date.now()};return {...s,dewdrops:s.dewdrops-750,inventory:s.inventory.map(x=>x.id==='primer'?{...x,quantity:x.quantity-3}:x),creatures:[...s.creatures,cragback],discoveries:[...new Set<WildSpecies>([...s.discoveries,'emberstride'])],achievements:[...new Set([...s.achievements,'Amber Reach Surveyor'])],lastAction:'Cragback joined your roster. Emberstride trails discovered.'}}
export function befriendLateCreature(s:GameState,species:'emberstride'|'veilfin'|'old-warden'):GameState{const configs={emberstride:{goal:5,item:'tea',qty:4,cost:1000,name:'Emberstride',rarity:'Mythic' as const,origin:'Befriended in Amber Reach',stats:{tracking:58,agility:94,resolve:62},next:'veilfin' as WildSpecies,achievement:'Ridge Runner'},veilfin:{goal:6,item:'bell',qty:2,cost:1250,name:'Veilfin',rarity:'Mythic' as const,origin:'Befriended in Cloudfen',stats:{tracking:95,agility:72,resolve:60},next:'old-warden' as WildSpecies,achievement:'Cloudfen Drifter'},'old-warden':{goal:7,item:'lamp',qty:2,cost:1500,name:'Old Warden',rarity:'Legendary' as const,origin:'Awakened in the Ruins',stats:{tracking:78,agility:40,resolve:99},next:null,achievement:'Warden of Bramblewake'}} as const;const config=configs[species];if((s.encounterProgress[species]??0)<config.goal||s.creatures.some(x=>x.species===species))return s;const item=s.inventory.find(x=>x.id===config.item);if((item?.quantity??0)<config.qty)return {...s,lastAction:`${config.qty} ${item?.name??'required supplies'} required.`};if(s.dewdrops<config.cost)return {...s,lastAction:`This expedition requires ${config.cost} Marks.`};const creature:OwnedCreature={id:`${species}-1`,species,name:config.name,rarity:config.rarity,bond:15,origin:config.origin,stats:config.stats,energy:100,maxEnergy:100,energyUpdatedAt:Date.now()};return {...s,dewdrops:s.dewdrops-config.cost,inventory:s.inventory.map(x=>x.id===config.item?{...x,quantity:x.quantity-config.qty}:x),creatures:[...s.creatures,creature],discoveries:config.next?[...new Set<WildSpecies>([...s.discoveries,config.next])]:s.discoveries,achievements:[...new Set([...s.achievements,config.achievement])],lastAction:`${config.name} joined your roster.${config.next?' The next trail is open.':' The Bramblewake roster is complete.'}`}}
export function selectCreature(s:GameState,id:string):GameState{const creature=s.creatures.find(x=>x.id===id);return creature?{...s,activeCreatureId:id,needs:{...s.needs,energy:creature.energy},lastAction:`${creature.name} is now your active companion.`}:s}

export function awardForage(s:GameState,marks:number,now=Date.now()):GameState{const today=dayKey(now);const plays=s.forageDate===today?s.foragePlays:0;if(plays>=3)return {...s,lastAction:'All three Mossmere contracts are complete for today.'};return {...s,dewdrops:s.dewdrops+Math.max(0,Math.floor(marks)),forageDate:today,foragePlays:plays+1,lastAction:`Forage Run reward: +${Math.max(0,Math.floor(marks))} Marks! Contract ${plays+1}/3 complete.`}}
