import type {GameState, OwnedCreature} from '../types';
import {activeCreature} from '../game';
import {hydrateCreature} from '../creatures/creatureEngine';
import {recordQuestEvent} from '../quests/questEngine';
import {hydrateCraftingState} from '../crafting/craftingEngine';
import {glassrootBySpecies,glassrootCreatures,type GlassrootSpecies} from './glassrootData';

const dayKey=(now=Date.now())=>new Date(now).toISOString().slice(0,10);
const weatherFor=(date:string):GameState['glassrootWeather']=>{const value=[...date].reduce((sum,char)=>sum+char.charCodeAt(0),0)%3;return value===0?'prism-squall':value===1?'mist':'clear'};
export const glassrootUnlocked=(state:GameState)=>state.creatures.some(creature=>creature.species==='old-warden')||state.glassrootStoryStep>0;
export function refreshGlassroot(state:GameState,now=Date.now()):GameState{const today=dayKey(now);return {...state,glassrootGatherDate:state.glassrootGatherDate===today?today:today,glassrootGatherPlays:state.glassrootGatherDate===today?state.glassrootGatherPlays:0,glassrootWeatherDate:today,glassrootWeather:state.glassrootWeatherDate===today?state.glassrootWeather:weatherFor(today)}}
export function gatherGlassroot(state:GameState,now=Date.now()):GameState{if(!glassrootUnlocked(state))return {...state,lastAction:'The Warden has not revealed the basin road yet.'};const fresh=refreshGlassroot(state,now);if(fresh.glassrootGatherPlays>=3)return {...fresh,lastAction:'The prism pools need time to settle. Return tomorrow.'};const play=fresh.glassrootGatherPlays+1;const drops:Record<string,number>={glassreed:2,saltbloom:play>=2?1:0,rootpearl:fresh.glassrootWeather==='prism-squall'&&play===3?1:0};const materials={...fresh.materials};for(const[id,amount]of Object.entries(drops))materials[id]=(materials[id]??0)+amount;const found=Object.keys(drops).filter(id=>drops[id]>0);const next={...fresh,materials,discoveredMaterials:[...new Set([...fresh.discoveredMaterials,...found])],glassrootGatherPlays:play,glassrootStoryStep:Math.max(1,fresh.glassrootStoryStep),dewdrops:fresh.dewdrops+35,lastAction:`Prism-pool sifting ${play}/3: +35 Marks, +2 Glassreed${drops.saltbloom?', +1 Saltbloom':''}${drops.rootpearl?', +1 Root Pearl':''}.`} as GameState;return recordQuestEvent(recordQuestEvent(hydrateCraftingState(next),'gather',Object.values(drops).reduce((a,b)=>a+b,0),now),'marksEarned',35,now)}
export function glassrootAvailable(state:GameState,species:GlassrootSpecies,now=Date.now()){const fresh=refreshGlassroot(state,now);const owns=(id:GlassrootSpecies)=>fresh.creatures.some(creature=>creature.species===id);const prerequisites:Record<GlassrootSpecies,boolean>={glintmoth:fresh.glassrootStoryStep>=1,reedstalker:owns('glintmoth'),flintcap:owns('reedstalker'),prismhart:owns('flintcap')&&fresh.glassrootWeather==='prism-squall',hollowhorn:owns('glintmoth')&&owns('reedstalker')&&owns('flintcap')&&owns('prismhart')};return {available:prerequisites[species],owned:owns(species),studied:(fresh.encounterDays[species]??[]).includes(dayKey(now)),weather:fresh.glassrootWeather}}
export function surveyGlassroot(state:GameState,species:GlassrootSpecies,now=Date.now()):GameState{const fresh=refreshGlassroot(state,now),status=glassrootAvailable(fresh,species,now),definition=glassrootBySpecies[species];if(status.owned)return fresh;if(!status.available)return {...fresh,lastAction:species==='prismhart'?'Prismhart appears only during a prism squall after Flintcap joins.':'Complete the previous basin chapter first.'};if(status.studied)return {...fresh,lastAction:'Today’s Glassroot notes are complete. Return tomorrow.'};const companion=activeCreature(fresh);if(companion.energy<10)return {...fresh,lastAction:`${companion.name} needs 10 Energy for this basin survey.`};const progress=Math.min(definition.goal,(fresh.encounterProgress[species]??0)+1),energy=companion.energy-10,today=dayKey(now);let next={...fresh,needs:{...fresh.needs,energy},creatures:fresh.creatures.map(entry=>entry.id===companion.id?{...entry,energy,energyUpdatedAt:now}:entry),encounterProgress:{...fresh.encounterProgress,[species]:progress},encounterDays:{...fresh.encounterDays,[species]:[...new Set([...(fresh.encounterDays[species]??[]),today])]},discoveries:[...new Set([...fresh.discoveries,species])],materials:{...fresh.materials,[species==='glintmoth'||species==='reedstalker'?'glassreed':species==='flintcap'?'saltbloom':'rootpearl']:(fresh.materials[species==='glintmoth'||species==='reedstalker'?'glassreed':species==='flintcap'?'saltbloom':'rootpearl']??0)+1},lastAction:`${definition.name} field note ${progress}/${definition.goal}.`} as GameState;if(progress===definition.goal){const creature=hydrateCreature({id:`${species}-1`,species,name:definition.name,rarity:definition.rarity,bond:species==='hollowhorn'?20:30,origin:'Befriended in Glassroot Basin',stats:definition.stats,energy:100,maxEnergy:100,energyUpdatedAt:now} as OwnedCreature);next={...next,creatures:[...next.creatures,creature],glassrootStoryStep:Math.max(next.glassrootStoryStep,glassrootCreatures.findIndex(entry=>entry.species===species)+2),achievements:[...new Set([...next.achievements,species==='hollowhorn'?'Glassroot Guardian':'Basin Naturalist'])],lastAction:species==='hollowhorn'?'Hollowhorn accepts your restored path. Glassroot Basin is complete.':`${definition.name} joined your roster. The next basin chapter is open.`}}return recordQuestEvent(recordQuestEvent(hydrateCraftingState(next),'encounter',1,now),'encounterSuccess',1,now)}
export function buyBasinSalve(state:GameState):GameState{const item=state.inventory.find(entry=>entry.id==='basin-salve');if(!item||state.dewdrops<item.price)return {...state,lastAction:'The Basin Exchange requires 70 Marks.'};return recordQuestEvent(recordQuestEvent({...state,dewdrops:state.dewdrops-item.price,inventory:state.inventory.map(entry=>entry.id==='basin-salve'?{...entry,quantity:entry.quantity+1}:entry),lastAction:'Nera packed a Basin Salve for the trail.'},'purchase'),'marksSpent',item.price)}
