import {CloudRain, Coins, Gem, Lock, MapPinned, PackageOpen, PawPrint, Sparkles} from 'lucide-react';
import type {GameState} from '../types';
import {buyBasinSalve,gatherGlassroot,glassrootAvailable,glassrootUnlocked,refreshGlassroot,surveyGlassroot} from './glassrootEngine';
import {glassrootCreatures} from './glassrootData';

const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;
const weatherLabels={clear:'Stillwater night',mist:'Rootmist', 'prism-squall':'Prism squall'} as const;
export function GlassrootPage({state,act}:{state:GameState;act:(state:GameState)=>void}){
 const fresh=refreshGlassroot(state),unlocked=glassrootUnlocked(fresh),salves=fresh.inventory.find(item=>item.id==='basin-salve')?.quantity??0;
 if(!unlocked)return <section className="page glassroot-page locked-region"><header><p>Uncharted route</p><h1>Beyond the Warden’s road</h1><span>The Old Warden guards a path absent from every current map.</span></header><div className="region-lock"><Lock/><h2>Glassroot Basin is sealed</h2><p>Complete the Old Warden encounter to reveal the basin crossing.</p></div></section>;
 return <section className="page glassroot-page"><header><p>New region · The outer archipelago</p><h1>Glassroot Basin</h1><span>Follow moonlit roots across flooded flats, weather prism squalls, and restore the guardian’s five forgotten markers.</span></header>
  <div className={`glassroot-hero weather-${fresh.glassrootWeather}`} style={{backgroundImage:`url(${asset('glassroot-basin.png')})`}}><div className="glassroot-weather"><CloudRain/><small>Regional condition</small><b>{weatherLabels[fresh.glassrootWeather]}</b><span>{fresh.glassrootWeather==='prism-squall'?'Rare trails and Root Pearls are visible.':fresh.glassrootWeather==='mist'?'Tracking signs are muted in the rootmist.':'The pools are calm and clear.'}</span></div><div className="glassroot-map-label"><MapPinned/><b>Rootbridge Exchange</b><span>Guardian shrine · 4 crossings</span></div></div>
  <section className="basin-overview"><article><small>Regional storyline</small><h2>The Five Root Markers</h2><p>Trailkeeper Nera believes the basin’s flooded roads were deliberately silenced. Each creature remembers a different part of the route.</p><b>Chapter {Math.min(5,Math.max(1,fresh.glassrootStoryStep))}/5</b></article><article><small>Gathering activity</small><h2>Prism-pool sifting</h2><p>Separate Glassreed and Saltbloom without stripping the pools. Three careful contracts return each day.</p><button disabled={fresh.glassrootGatherPlays>=3} onClick={()=>act(gatherGlassroot(fresh))}><Gem/> {fresh.glassrootGatherPlays>=3?'Pools settling until tomorrow':`Sift a pool · ${fresh.glassrootGatherPlays}/3`}</button></article></section>
  <section className="basin-vendor"><div><small>Regional vendor · Nera Vale</small><h2>Rootbridge Exchange</h2><p>“Take only what the basin can replace.”</p></div><article><span>🫙</span><div><b>Basin Salve</b><small>Restorative · 70 Marks · Owned {salves}</small></div><button disabled={fresh.dewdrops<70} onClick={()=>act(buyBasinSalve(fresh))}><Coins/> Buy</button></article><article className="vendor-notes"><PackageOpen/><div><b>Local patterns</b><small>Rootglass Stool, Prism-Rain Cloak, and Hollowhorn Chime recipes appear in Crafting as their materials are discovered.</small></div></article></section>
  <div className="region-creatures"><div><p>Regional field journal</p><h2>Creatures of Glassroot</h2></div>{glassrootCreatures.map((definition,index)=>{const status=glassrootAvailable(fresh,definition.species),progress=fresh.encounterProgress[definition.species]??0;return <article className={`${status.available?'available':'locked'} ${status.owned?'owned':''}`} key={definition.species}><img src={asset(`creature-${definition.species}.png`)} alt={status.available||status.owned?definition.name:'Undiscovered Glassroot creature'}/><div><small>{definition.rarity} · {definition.kind}</small><h3>{status.available||status.owned?definition.name:'Unknown basin creature'}</h3><p>{status.available||status.owned?definition.story:definition.condition}</p><div className="basin-progress"><i style={{width:`${progress/definition.goal*100}%`}}/><span>{progress}/{definition.goal} field notes</span></div>{status.owned?<b className="basin-complete"><PawPrint/> Joined your roster</b>:status.available?<button disabled={status.studied} onClick={()=>act(surveyGlassroot(fresh,definition.species))}><Sparkles/> {status.studied?'Notes complete today':index===4?'Restore a root marker':'Record field signs'}</button>:<span className="basin-condition"><Lock/> {definition.condition}</span>}</div></article>})}</div>
 </section>
}
